### ISSUE TITLE
Would u support the latest Facebook UI?

### ISSUE THREAD

**Issue by hlqf** [JosephDillman/Facebook-Comment-Cleaner-Chrome-Extension-#1]
Hi,
We tried on the latest FB UI, it seems your extension didn't work on it. Do u have plan to support it?

**Comment by JosephDillman** [comment]
I don’t believe I have access to facebooks new UI (probably a region issue) and I unfortunately don’t plan on supporting it as of now. Apologies.

**Comment by JosephDillman** [comment]
Since writing my last comment I have gained access to the new UI and updated the extension to support the new UI. Changes have been published!
